// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardLeft(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("span", {
                            children: "Nextmed",
                            className: "font-semibold tracking-widest uppercase"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h1", {
                                    children: props.title,
                                    className: "text-3xl/tight mb-4"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: props.content,
                                    className: "text-gray-200 font-normal leading-relaxed"
                                  })
                            ]
                          })
                    ],
                    className: "login-left"
                  }),
              className: "xl:col-span-2 lg:col-span-1 hidden lg:block"
            });
}

var make = CardLeft;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
