// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("button", {
                    children: props.label,
                    className: "bg-sky-600 text-white text-sm rounded-lg px-6 py-2.5 hover:bg-sky-700 hover:shadow-sm",
                    onClick: props.onClick
                  }),
              className: "flex justify-end items-center gap-6 mt-8"
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
