// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../../components/button/Button.res.mjs";
import * as CardBio from "../../components/card/bio/CardBio.res.mjs";
import * as ListDetail from "../../components/list/ListDetail.res.mjs";
import * as Dom_storage from "rescript/lib/es6/dom_storage.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function ProfilePage(props) {
  var isLoggedIn = Dom_storage.getItem("isLoggedIn", localStorage);
  var match = React.useState(function () {
        if (isLoggedIn !== undefined) {
          return JSON.parse(isLoggedIn);
        } else {
          return {
                  fullName: "",
                  email: "",
                  pwd: ""
                };
        }
      });
  var user = match[0];
  var onClick = function (_evt) {
    Dom_storage.removeItem("isLoggedIn", localStorage);
    RescriptReactRouter.push("/");
  };
  React.useEffect((function () {
          if (isLoggedIn === undefined) {
            RescriptReactRouter.push("/");
          }
          
        }), []);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx(CardBio.make, {
                            title: "Bio",
                            content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. uasi distinctio dolores illo aspernatur facere eius magnam magni",
                            src: "https://images.lifestyleasia.com/wp-content/uploads/2019/10/18094733/1128_01_2610.jpg?tr=w-1600"
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx("h1", {
                                                children: "Profile",
                                                className: "text-2xl/tight font-bold"
                                              })
                                        }),
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx(ListDetail.make, {
                                                  label: "Name",
                                                  content: user.fullName
                                                }),
                                            JsxRuntime.jsx(ListDetail.make, {
                                                  label: "Email",
                                                  content: user.email
                                                })
                                          ],
                                          className: "boxprofile-wrapper"
                                        }),
                                    JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx(Button.make, {
                                                label: "Logout",
                                                onClick: onClick
                                              }),
                                          className: "flex flex-wrap items-center justify-end gap-6 mt-8"
                                        })
                                  ],
                                  className: "boxprofile-container"
                                }),
                            className: "bg-white rounded-lg p-5 m-5"
                          })
                    ],
                    className: "container 2xl:px-[400px] xl:px-[400px]"
                  }),
              className: "profile-page"
            });
}

var make = ProfilePage;

export {
  make ,
}
/* react Not a pure module */
