// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardContainer$CardContainer(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("div", {
                          children: props.children,
                          className: "login-cardwrapper"
                        }),
                    className: "login-card"
                  }),
              className: "container 2xl:px-80 xl:px-52"
            });
}

var CardContainer = {
  make: CardContainer$CardContainer
};

export {
  CardContainer ,
}
/* react/jsx-runtime Not a pure module */
