// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardBio(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsx("img", {
                                        className: "w-full h-full rounded-full",
                                        src: props.src
                                      }),
                                  className: " justify-self-center w-[72px] h-[72px] rounded-full border border-gray-200"
                                }),
                            JsxRuntime.jsx("label", {
                                  children: props.title,
                                  className: "font-medium text-sm block mb-2"
                                }),
                            JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsx("p", {
                                        children: props.content,
                                        className: "text-gray-500 text-m rounded-lg py-2 px-2 w-full"
                                      }),
                                  className: " w-full h-full border border-gray-200 rounded-xl "
                                })
                          ],
                          className: "space-y-1 mt-1 grid"
                        }),
                    className: "bio-container"
                  }),
              className: "bg-white rounded-lg p-5 m-5"
            });
}

var make = CardBio;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
