// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../components/input/Input.res.mjs";
import * as React from "react";
import * as Button from "../../components/button/Button.res.mjs";
import * as CardLeft from "../../components/card/cardleft/CardLeft.res.mjs";
import * as CardRight from "../../components/card/cardright/CardRight.res.mjs";
import * as CardContainer from "../../components/card/cardcontainer/CardContainer.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function SignupPage(props) {
  var match = React.useState(function () {
        return "";
      });
  var setFullName = match[1];
  var fullName = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setEmail = match$1[1];
  var email = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPwd = match$2[1];
  var pwd = match$2[0];
  var onClick = function (_evt) {
    var newUser = {
      fullName: fullName,
      email: email,
      pwd: pwd
    };
    console.log(newUser);
    setFullName(function (param) {
          return "";
        });
    setEmail(function (param) {
          return "";
        });
    setPwd(function (param) {
          return "";
        });
    RescriptReactRouter.push("/");
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs(CardContainer.CardContainer.make, {
                    children: [
                      JsxRuntime.jsx(CardLeft.make, {
                            title: "Welcome to ours members!!",
                            content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                          }),
                      JsxRuntime.jsxs(CardRight.make, {
                            header: "Sign Up",
                            subhead: "Welcome to ours members",
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(Input.make, {
                                            label: "Full Name",
                                            type_: "text",
                                            name: "fullName",
                                            placeholder: "Enter your name",
                                            value: fullName,
                                            onChange: (function (e) {
                                                setFullName(e.target.value);
                                              })
                                          }),
                                      JsxRuntime.jsx(Input.make, {
                                            label: "Email",
                                            type_: "text",
                                            name: "email",
                                            placeholder: "Enter your email",
                                            value: email,
                                            onChange: (function (e) {
                                                setEmail(e.target.value);
                                              })
                                          }),
                                      JsxRuntime.jsx(Input.make, {
                                            label: "Password",
                                            type_: "password",
                                            name: "pwd",
                                            placeholder: "Enter your password",
                                            value: pwd,
                                            onChange: (function (e) {
                                                setPwd(e.target.value);
                                              })
                                          })
                                    ],
                                    className: "boxregister-section"
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx(Button.make, {
                                          label: "Sign Up",
                                          onClick: onClick
                                        }),
                                    className: "flex justify-end items-center gap-6 mt-8"
                                  })
                            ]
                          })
                    ]
                  }),
              className: "login-page"
            });
}

var make = SignupPage;

export {
  make ,
}
/* Input Not a pure module */
