// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SigninPage from "./pages/signin/SigninPage.res.mjs";
import * as SignupPage from "./pages/signup/SignupPage.res.mjs";
import * as ProfilePage from "./pages/profile/ProfilePage.res.mjs";
import * as NotFoundPage from "./pages/notfound/NotFoundPage.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

import './App.css'
;

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var match$1;
  if (match) {
    switch (match.hd) {
      case "home" :
          match$1 = match.tl ? JsxRuntime.jsx(NotFoundPage.make, {}) : JsxRuntime.jsx(ProfilePage.make, {});
          break;
      case "signup" :
          match$1 = match.tl ? JsxRuntime.jsx(NotFoundPage.make, {}) : JsxRuntime.jsx(SignupPage.make, {});
          break;
      default:
        match$1 = JsxRuntime.jsx(NotFoundPage.make, {});
    }
  } else {
    match$1 = JsxRuntime.jsx(SigninPage.make, {});
  }
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("main", {
                    children: match$1
                  })
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
