// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardRight(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: props.header,
                              className: "text-2xl/tight mb-3"
                            }),
                        JsxRuntime.jsx("p", {
                              children: props.subhead,
                              className: "text-sm font-medium leading-relaxed"
                            })
                      ]
                    }),
                props.children
              ],
              className: "boxregister-container"
            });
}

var make = CardRight;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
